### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/ALKiln#291]
It might be useful to do a PR for just cleaning up some stuff. Remove old comments, do some small clarification refactors. I think a specific list would help, so I'll jot things down when they occur to me that don't necessarily need a PR of their own.

- [x] In `scope.processVar()`, instead of using `prev_length > fields_to_set.length && fields_to_set.length > 0` for the `while` check, make a var called `something_was_set`. In the loop, set it to `false` then later set it to `true` if something is set. If nothing was set, no new fields will be revealed so we don't need to loop again.
- [x] #167, buffer
- [x] #46, add link to da where encoding happens
- [x] #44, decoder fallback string
- [x] #43, remove `scope.checkboxNameAttribute()`
- [ ] Remove scope.js functions that are no longer being used in steps.js or scope.js
- [x] #42, add comment on error checking
- [x] #41, remove unnecessary logic check in navigation if it's still there
- [x] #39, add clarifying address comments
- [ ] Change name of `scope.setField()` or get rid of it if we can [The PR is the thing that added `setFields()`, plural. We need to rename or get rid of the singular one.]

**Comment by plocket** [comment]
Let's link some other items in here that we consider small clean up jobs.

**Comment by niharikasingh** [comment]
https://github.com/plocket/docassemble-cucumber/pull/307 closes the first item in this list.
